---
- name: enable_capsule_required_repos | Enable Repositories to the Capsule
  command: "{{ item }}"
  when: satellite_version == "6.2"
  tags:
    - enable_capsule_required_repos
  ignore_errors: yes
  with_items:
   - /usr/bin/hammer -u admin -p "{{ foreman_admin_password }}" repository-set enable --name 'Red Hat Enterprise Linux 7 Server (RPMs)' --organization "{{ foreman_initial_organization }}" --product 'Red Hat Enterprise Linux Server' --basearch x86_64 --releasever 7Server
   - /usr/bin/hammer -u admin -p "{{ foreman_admin_password }}" repository-set enable --name 'Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server' --organization "{{ foreman_initial_organization }}" --product 'Red Hat Software Collections (for RHEL Server)' --basearch x86_64 --releasever 7Server
   - /usr/bin/hammer -u admin -p "{{ foreman_admin_password }}" repository-set enable --name 'Red Hat Satellite Capsule 6.2 (for RHEL 7 Server) (RPMs)' --organization "{{ foreman_initial_organization }}" --product 'Red Hat Satellite Capsule' --basearch x86_64
  delegate_to: "{{ satellite_server }}"

- name: enable_capsule_required_repos | Enable Repositories to the Capsule
  command: "{{ item }}"
  when: satellite_version == "6.3"
  tags:
    - enable_capsule_required_repos
  ignore_errors: yes
  with_items:
   - /usr/bin/hammer -u admin -p "{{ foreman_admin_password }}" repository-set enable --name 'Red Hat Enterprise Linux 7 Server (RPMs)' --organization "{{ foreman_initial_organization }}" --product 'Red Hat Enterprise Linux Server' --basearch x86_64 --releasever 7Server
   - /usr/bin/hammer -u admin -p "{{ foreman_admin_password }}" repository-set enable --name 'Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server' --organization "{{ foreman_initial_organization }}" --product 'Red Hat Software Collections (for RHEL Server)' --basearch x86_64 --releasever 7Server
   - /usr/bin/hammer -u admin -p "{{ foreman_admin_password }}" repository-set enable --name 'Red Hat Satellite Capsule 6.3 (for RHEL 7 Server) (RPMs)' --organization "{{ foreman_initial_organization }}" --product 'Red Hat Satellite Capsule' --basearch x86_64
   - /usr/bin/hammer -u admin -p "{{ foreman_admin_password }}" repository-set enable --name 'Red Hat Satellite Capsule 6.3 - Puppet 4 (for RHEL 7 Server) (RPMs)' --organization "{{ foreman_initial_organization }}" --product 'Red Hat Satellite Capsule' --basearch x86_64
  delegate_to: "{{ satellite_server }}"

- name: enable_capsule_required_repos | Enable Repositories to the Capsule
  command: "{{ item }}"
  when: satellite_version == "6.4"
  tags:
    - enable_capsule_required_repos
  ignore_errors: yes
  with_items:
   - /usr/bin/hammer -u admin -p "{{ foreman_admin_password }}" repository-set enable --name 'Red Hat Enterprise Linux 7 Server (RPMs)' --organization "{{ foreman_initial_organization }}" --product 'Red Hat Enterprise Linux Server' --basearch x86_64 --releasever 7Server
   - /usr/bin/hammer -u admin -p "{{ foreman_admin_password }}" repository-set enable --name 'Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server' --organization "{{ foreman_initial_organization }}" --product 'Red Hat Software Collections (for RHEL Server)' --basearch x86_64 --releasever 7Server
   - /usr/bin/hammer -u admin -p "{{ foreman_admin_password }}" repository-set enable --name 'Red Hat Satellite Maintenance 6 (for RHEL 7 Server) (RPMs)' --organization "{{ foreman_initial_organization }}" --product 'Red Hat Enterprise Linux Server' --basearch x86_64
   - /usr/bin/hammer -u admin -p "{{ foreman_admin_password }}" repository-set enable --name 'Red Hat Ansible Engine 2.6 RPMs for Red Hat Enterprise Linux 7 Server' --organization "{{ foreman_initial_organization }}" --product 'Red Hat Ansible Engine' --basearch x86_64
   - /usr/bin/hammer -u admin -p "{{ foreman_admin_password }}" repository-set enable --name 'Red Hat Satellite Capsule 6.4 (for RHEL 7 Server) (RPMs)' --organization "{{ foreman_initial_organization }}" --product 'Red Hat Satellite Capsule' --basearch x86_64
  delegate_to: "{{ satellite_server }}"
