---
- name: registration | Register machine with RHSM
  command: /usr/bin/subscription-manager register --username={{ rhsm_user }} --password={{ rhsm_password }} --name={{ hostname_full }}
  tags:
    - rhsm
  ignore_errors: yes
  no_log: yes

- name: registration | Get Satellite pool ID
  shell: /usr/bin/subscription-manager list --all --available --matches="Red Hat Satellite" | awk '/Pool ID/ {print $3}' | head -1
  tags:
    - rhsm
  register: pool_id
  ignore_errors: yes

- name: registration | Attach machine with Satellite pool ID
  command: /usr/bin/subscription-manager attach --pool={{ pool_id.stdout }}
  tags:
    - rhsm
  ignore_errors: yes
